# Generated by Django 5.0.6 on 2024-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.CharField(default='images/default.png', max_length=255),
        ),
    ]
